### ISSUE TITLE
CONT ged stripped of spaces

### ISSUE THREAD

**Issue by irdroid3** [dijxtra/simplepyged#5]
Hi Nikola, I am using simplepyged to extract info from a GEDCOM export file - so far, so good - your library is making this easy...  Thank you.

But - I notice that leading spaces are being removed from notes.  EG in the GEDCOM file =

0 @NI085@ NOTE
1 CONT  Isabella DAWSON   Household
1 CONT     Female  
1 CONT   Other Information:
1 CONT     Birth Year <1841> 
1 CONT     Birthplace Washington, Durham, England 
1 CONT     Age 40 
1 CONT     Occupation  
1 CONT     Marital Status M <Married> 
1 CONT     Head of Household Joseph DAWSON
1 CONT   RelationWife 

But when I print the gedcom as seen in python (EG "print note.gedcom()"), I get -

0 @NI085@ NOTE
1 CONT Isabella DAWSON Household
1 CONT Female
1 CONT Other Information:
1 CONT Birth Year <1841>
1 CONT Birthplace Washington, Durham, England
1 CONT Age 40
1 CONT Occupation
1 CONT Marital Status M <Married>
1 CONT Head of Household Joseph DAWSON
1 CONT RelationWife

A minor point, but I think it would be better to present the data as it was in the gedcom.
A welcome your feedback, Regards, Ian
.

**Comment by irdroid3** [comment]
I am new to github, so am not sure how to submit fix suggestions...   so I will do it here...

I have made the following changes to my copy of gedcom.py :

1) in the proc - "def _parse_line(self,number,line):" add "line" as another parm passed to _value() :
v = self._value(number,parts,place,line)

2) change the proc "def _value(self,number,parts,place,line):" to :
    def _value(self,number,parts,place,line):
        if len(parts) <= place:
            return ''
        # rest of the line should be ours
        v = ''
        if place < len(parts):
            n = place
            start = line.find(' ')
            while start >= 0 and n > 1:
                start = line.find(' ', start+1)
                n -= 1
            place = len(parts)
            v = string.join([line[start+1:]])
        v = v.rstrip()
        return v

This change passes the remainder of the gedcom line after the level,id,keyword arguments as a value, and maintains whitespace.

**Comment by irdroid3** [comment]
ps, sorry about the typeface - monospaced would have been better for code (I dont think I can format these comments, can I ?)

**Comment by dijxtra** [comment]
Let me see if I understood your problem correctly. Your problem is that there are more than one space between "CONT" and start of the value, right? So, your input data is:

```
0 @NI085@ NOTE
1 CONT      Isabella DAWSON Household
```

and the parser outputs it as:

```
0 @NI085@ NOTE
1 CONT Isabella DAWSON Household
```

Is that your problem?

**Comment by irdroid3** [comment]
That is prety much the problem - any multiple-spaces after the CONT is reduced to one space.  As the value is split into striped words and reassembled with one space between each word.
Some of my gedcom notes are cut & paste from reports and are column alligned (in mono spaced text)...
I figure that if a value is saved with multiple spaces then the user meant it to be.
Regards, Ian
.

**Comment by dijxtra** [comment]
There, I fixed it in commit 88122c. Please see if now everything is OK.

**Comment by irdroid3** [comment]
I tested my prog and that works for me, many thanks.  Ian
